federated-catalog:
  nameOverride: federated-catalog

  storage:
    enabled: true
    size: 1Gi
    path: "/mnt/data"

  postgresql:
    enabled: true
    auth:
      postgresPassword: "xfsc4Ntt!"
      username: "postgres"
      password: "xfsc4Ntt!"
      database: postgres
    image:
      registry: bitnamilegacy
      repository: postgresql
      tag: 16.2.0-debian-12-r8
    primary:
      persistence:
        size: 5Gi