#deployment for fdederated catalog(an EDC component)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "app.chartname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ include "app.revision" . }}
    app.kubernetes.io/part-of: federated-catalog
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        {{- include "app.metricsAnnotations" . | nindent 8 }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      securityContext:
{{- include "app.securitycontext" . | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}

      #container specification 
      containers:
      - name: {{ template "app.chartname" . }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}

        #environment variables
        env:
        - name: LOG_LEVEL
          value: "{{ .Values.log.level | default "info" }}"
        - name: EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS
          value: "{{ .Values.config.cacheExecutionDelay }}"
        - name: EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS
          value: "{{ .Values.config.cacheExecutionPeriod }}"
        - name: EDC_CATALOG_CACHE_PARTITION_NUM_CRAWLERS
          value: "{{ .Values.config.cachePartitionNumCrawlers }}"
        - name: WEB_HTTP_PORT
          value: "{{ .Values.config.http.port }}"
        - name: WEB_HTTP_PATH
          value: "{{ .Values.config.http.path }}"
        - name: WEB_HTTP_CATALOG_PORT
          value: "{{ .Values.config.catalog.port }}"
        - name: WEB_HTTP_CATALOG_PATH
          value: "{{ .Values.config.catalog.path }}"
        - name: EDC_HTTP_DISABLE_TLS
          value: "{{ .Values.config.disableTLS | default "false" }}"
        - name: EDC_WEB_REST_CORS_ENABLED
          value: "true"
        - name: EDC_WEB_REST_CORS_HEADERS
          value: "origin, content-type, accept, authorization, x-api-key"
        - name: EDC_WEB_REST_CORS_METHODS
          value: "POST, OPTIONS"

        - name: EDC_DATASOURCE_DEFAULT_URL
          value: jdbc:postgresql://{{ include "app.chartname" . }}-postgresql-hl.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgresql.auth.database }}
        - name: EDC_DATASOURCE_DEFAULT_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: EDC_DATASOURCE_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "app.chartname" . }}-postgresql
              key: postgres-password
        - name: EDC_SQL_SCHEMA_AUTOCREATE
          value: "true"
        {{- if .Values.secretEnv }}
        {{- range $key, $value := .Values.secretEnv }}
          - name: "{{ $key }}"
            valueFrom:
              secretKeyRef:
                name: "{{ $value.name }}"
                key: "{{ $value.key }}"
        {{- end }}
        {{- end }}
{{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 8 }}
{{- end }}
        volumeMounts:
        - name: json-config-volume
          mountPath: /etc/config

        #port specification
        ports:
        {{- if .Values.metrics.enabled }}
        - name: monitoring
          containerPort: {{ .Values.metrics.port }}
        {{- end }}
        - name: http
          containerPort: {{ .Values.config.http.port }}
        - name: catalog
          containerPort: {{ .Values.config.catalog.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.config.http.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 2
          timeoutSeconds: 5

        #resource requests and limits
        resources:
{{ toYaml .Values.resources | indent 10 }}
      
      #volume specification
      #to be removed when participants are stored in a database
      #only for testing purposes
      volumes:
      - name: json-config-volume
        configMap:
          name: "{{ template "app.chartname" . }}-participants-configmap"
